[package]
name = "devctl"
version = "9.0.1"
edition = "2021"
description = "Easily start developing in monorepos with docker-compose"
license = "MIT"
repository = "https://github.com/maktouch/devctl"

[[bin]]
name = "devctl"
path = "src/main.rs"

[lib]
name = "devctl"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "2"
comfy-table = { version = "7", features = ["custom_styling"] }
dialoguer = "0.11"
dirs = "5"
indexmap = { version = "2", features = ["serde"] }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
ureq = "2"

[dev-dependencies]
tempfile = "3"
